version: '3'

services:
  userService:
    image: gcr.io/micro-services-406818/ms_nodejs_rabbitmq-userservice-v2:arm64
    ports:
      - '3001:3001'

  orderService:
    image: gcr.io/micro-services-406818/ms_nodejs_rabbitmq-orderservice-v2:arm64
    ports:
      - '3002:3002'

  rabbitmq:
    image: gcr.io/micro-services-406818/ms_nodejs_rabbitmq-rabbitmq-v2:arm64
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
