# Use an official RabbitMQ image
FROM rabbitmq:management

# Expose the ports for RabbitMQ (AMQP) and the management console
EXPOSE 5672 15672

# Set the default RabbitMQ username and password
ENV RABBITMQ_DEFAULT_USER=guest
ENV RABBITMQ_DEFAULT_PASS=guest
