apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service-container
          image: gcr.io/micro-services-406818/ms_nodejs_rabbitmq-orderservice:$_TAG
          ports:
            - containerPort: 3002
