steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/micro-services-406818/ms_nodejs_rabbitmq-userservice:$_TAG',
        '.',
      ]
images:
  - 'gcr.io/micro-services-406818/ms_nodejs_rabbitmq-userservice:$_TAG'
options:
  logging: CLOUD_LOGGING_ONLY
