name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'userService/**'
      - 'orderService/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@v352.0.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --config userService/cloudbuild.yaml userService
          gcloud builds submit --config orderService/cloudbuild.yaml orderService

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to GKE
        run: |
          kubectl apply -f userService/kubernetes/deployment.yaml
          kubectl apply -f orderService/kubernetes/deployment.yaml
