name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'userService/**'
      - 'orderService/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '>= 363.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and Push Docker Image for userService
        run: |
          gcloud builds submit --config userService/cloudbuild.yaml --async userService

      - name: Build and Push Docker Image for orderService
        run: |
          gcloud builds submit --config orderService/cloudbuild.yaml --async orderService

  deploy:
    needs: build
    runs-on: ubuntu-latest

    env:
      GCP_K8_CLUSTER: ${{ secrets.GCP_K8_CLUSTER }}

    steps:
      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '>= 363.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set Kubernetes Context
        run: kubectl config use-context $GCP_K8_CLUSTER
        # Replace YOUR_CLUSTER_CONTEXT with the actual name of your GKE cluster.

      - name: Debug kubectl config
        run: kubectl config view

      - name: Debug kubectl context
        run: kubectl config current-context

      - name: Deploy to GKE - userService
        run: |
          kubectl apply -f userService/deployment.yaml

      - name: Deploy to GKE - orderService
        run: |
          kubectl apply -f orderService/deployment.yaml
